"""add depends_on_job_id for workflow dependencies

Revision ID: 99de1e4bbc09
Revises: e49d438f30db
Create Date: 2026-07-04 23:16:31.523249

"""
from alembic import op
import sqlalchemy as sa


revision = '99de1e4bbc09'
down_revision = 'e49d438f30db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('depends_on_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'jobs', ['depends_on_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'depends_on_job_id')
    # ### end Alembic commands ###
