"""add dead_letter_queue table

Revision ID: e49d438f30db
Revises: 1a540578053b
Create Date: 2026-07-04 17:13:33.442115

"""
from alembic import op
import sqlalchemy as sa


revision = 'e49d438f30db'
down_revision = '1a540578053b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('final_error', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_queue_job_id'), 'dead_letter_queue', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_queue_job_id'), table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    # ### end Alembic commands ###
